name: Keep Supabase Alive

on:
  schedule:
    # Menjalankan setiap 5 hari sekali pada pukul 2 pagi UTC.
    # Cukup untuk mencegah pause (yang butuh 7 hari tidak aktif).
    - cron: '0 2 */5 * *'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    # PENTING: Karena Anda menyimpan secret di environment "Production",
    # kita perlu menunjuk ke environment tersebut di sini agar bisa diakses.
    environment: Production
    steps:
      - name: Ping Supabase Database
        run: |
          # Perintah ini akan MENAMBAHKAN baris baru ke tabel setiap kali berjalan
          curl -X POST \
            "${{ secrets.SUPABASE_URL }}/rest/v1/keep_alive_logs" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            -d '{}'